//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public int no_consulta { get; set; }
        public int cod_cita { get; set; }
        public string id_paciente { get; set; }
        public int medico { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string examenes { get; set; }
        public string archivos { get; set; }
        public string diagnostico { get; set; }
        public string receta_medica { get; set; }
    
        public virtual cita cita { get; set; }
        public virtual medico medico1 { get; set; }
    }
}
