//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public int no_paciente { get; set; }
        public string id_paciente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string tipo_sangre { get; set; }
        public string genero { get; set; }
        public string ocupacion { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string direccion { get; set; }
        public int no_medico { get; set; }
        public string informacion { get; set; }
        public string usuario_creador { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
